= Calavera2 project

This is a rewrite of the Calavera project, using Docker instead of Vagrant.

== IP ranges for containers

* Team1 gets 203.0.113.1 - .10 for ip and ports 1000-2000
* Team2 gets 203.0.113.2 - .20 for ip and ports 2000-3000
* Team3 gets 203.0.113.3 - .30 for ip and ports 3000-4000
* Team4 gets 203.0.113.4 - .40 for ip and ports 4000-5000

For example, team1 gets 201.0.113.1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19

== 11/3 assignment

Every team should identify at least one "committer."

*On Github,* that person should fork the Calavera2 repository to their account, and clone it down to their home directory on the server.

*On the server,* be careful to save any previous work, for example if you already have directly cloned dm-academy/Calavera2 you should rename that directory.

If you have completed some part of the work to your satisfaction, commit it to your Github fork and issue a pull request for me.

You may need to copy from your old dm-academy/Calavera2 repository to your new forked/cloned version.

If you have any questions, please ask. Don't want anyone to lose any work.
